version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev", "--", "--host"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./client:/app
    command: ["npm", "start"]
